version: '3'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: toosafinder
  toosa-back:
    image: toosafinder/toosafinder-back:dev
    depends_on: 
      - postgres
    ports:
      - 8081:8081
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: 123321
      DB_HOSTNAME: postgres
